version: '3.8'

services:
  # AutoCrack 后端服务
  autocrack-backend:
    build: .
    container_name: autocrack-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///autocrack.db
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - autocrack-db:/app/database
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - autocrack-network

  # Redis 缓存服务
  redis:
    image: redis:7-alpine
    container_name: autocrack-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - autocrack-network
    command: redis-server --appendonly yes

  # Nginx 反向代理 (可选)
  nginx:
    image: nginx:alpine
    container_name: autocrack-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./frontend/build:/usr/share/nginx/html:ro
    depends_on:
      - autocrack-backend
    restart: unless-stopped
    networks:
      - autocrack-network

volumes:
  autocrack-db:
    driver: local
  redis-data:
    driver: local

networks:
  autocrack-network:
    driver: bridge